# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#   
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Major.create(:name => 'Daley', :city => cities.first)


# These are random articles from today's slashdot
Articles = Article.create( [
        {:title => "Research Finds That Electric Fields Help Neurons Fire",
         :author => "An anonymous reader",
         :body => "[T]he brain is enveloped in countless overlapping electric fields, generated by the neural circuits of scores of communicating neurons. ... New work ... suggests that the fields do much more—and that they may, in fact, represent an additional form of neural communication. \"In other words,\" says Anastassiou, the lead author of a paper about the work appearing in the journal Nature Neuroscience (abstract), \"while active neurons give rise to extracellular fields, the same fields feed back to the neurons and alter their behavior,\" even though the neurons are not physically connected—a phenomenon known as ephaptic (or field) coupling. \"So far, neural communication has been thought to occur almost entirely via traffic involving synapses, the junctions where one neuron connects to the next one. Our work suggests an additional means of neural communication through the extracellular space independent of synapses.\"' If this work is replicated, it could reveal that the brain is even more complicated and sophisticated than we thought — and raise new concerns about whether our cellphones and other electronic gizmos are affecting brain activity and memory. This is truly paradigm-busting work."

        },
        {:title => "Canada Courts Quash Gov't Decision On Globalive",
         :author => "sitkill",
         :body => "A Canadian Federal Court ruling has rejected the Tory Cabinet's decision to overturn a CRTC mandate not allowing Globalive (which is more commonly known in Canada as the mobile carrier Wind) to operate in Canada. This is a small vindication to the embattled CRTC, which has been recently in the spotlight for its decision on usage based billing, drawing criticism from the Tory Cabinet. The CEO, Mr. Lacavera, stressed that this would not result in Globalive's Wind Mobile being shut down, simply that it would require another round of wrangling with the regulator over how much foreign influence is acceptable in a Canadian telecommunications company."
        },
        {:title => "Bill Gates Says Anti-Vaccine Effort Kills Children", 
         :author => "Hugh Pickens",
         :body => "CNN has an interesting interview with Bill Gates who says that unbelievable progress is being made in both inventing new vaccines and making sure they get out to all the children who need them. The improvements could cut the number of children who die every year from about 9 million to half that. But Gates has harsh words for those who engage in anti-vaccine efforts, especially Dr. Andrew Wakefield, who falsified data to 'prove' a fraudulent link between vaccines and autism. 'It's an absolute lie that has killed thousands of kids,' says Gates. 'Because the mothers who heard that lie, many of them didn't have their kids take either pertussis or measles vaccine, and their children are dead today."
        },
        {:title => "US Gov't Pushing News Through China's Great Firewall",
         :author => "eldavojohn",
         :body => "The US government's Broadcasting Board of Governors has revealed in a completed FOIA request the development, testing and planned use of Feed Over E-mail (FOE) to push news through China's firewall. This FOIA request (PDF) indicates that the US government is interested in making sure Chinese people receive up-to-date news, and it wants to expand the arsenal of anti-censorship tools (for news at least). The FOE project is GPLv3 and maintained by Sho Ho of BBG."
        },
        {:title => "Pentagon Sets Tone For Future Space Exploration",
         :author => "coondoggie",
         :body => "It obviously leans heavily on the military's concerns for outer space exploration, but the National Security Space Strategy (PDF) released yesterday by the Department of Defense outlines concerns like protection from space junk and system security that all space travelers in theory would want addressed. The NSSS document emphasizes the Obama administration's desire to protect US space assets and to further commercialize space but also to ensure that the US and international partners have unfettered access to outer space."
        }
    ])
