# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#   
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Major.create(:name => 'Daley', :city => cities.first)

# These are random authors
authors = Author.create( [
	{:name => "An anonymous reader"},
	{:name => "sitkill"},
	{:name => "Hugh Pickens"},
	{:name => "eldavojohn"},
	{:name => "itwbennett"},
	{:name => "Kilrah_il"},
	{:name => "coondoggie"},
	{:name => "adeelarshad82"},
 ])

# These are random articles from today's slashdot
Articles = Article.create( [
        {:title => "Research Finds That Electric Fields Help Neurons Fire",
         :author => authors[0],
         :body => "[T]he brain is enveloped in countless overlapping electric fields, generated by the neural circuits of scores of communicating neurons. ... New work ... suggests that the fields do much more—and that they may, in fact, represent an additional form of neural communication. \"In other words,\" says Anastassiou, the lead author of a paper about the work appearing in the journal Nature Neuroscience (abstract), \"while active neurons give rise to extracellular fields, the same fields feed back to the neurons and alter their behavior,\" even though the neurons are not physically connected—a phenomenon known as ephaptic (or field) coupling. \"So far, neural communication has been thought to occur almost entirely via traffic involving synapses, the junctions where one neuron connects to the next one. Our work suggests an additional means of neural communication through the extracellular space independent of synapses.\"' If this work is replicated, it could reveal that the brain is even more complicated and sophisticated than we thought — and raise new concerns about whether our cellphones and other electronic gizmos are affecting brain activity and memory. This is truly paradigm-busting work."

        },
        {:title => "Canada Courts Quash Gov't Decision On Globalive",
         :author => authors[1],
         :body => "A Canadian Federal Court ruling has rejected the Tory Cabinet's decision to overturn a CRTC mandate not allowing Globalive (which is more commonly known in Canada as the mobile carrier Wind) to operate in Canada. This is a small vindication to the embattled CRTC, which has been recently in the spotlight for its decision on usage based billing, drawing criticism from the Tory Cabinet. The CEO, Mr. Lacavera, stressed that this would not result in Globalive's Wind Mobile being shut down, simply that it would require another round of wrangling with the regulator over how much foreign influence is acceptable in a Canadian telecommunications company."
        },
        {:title => "Bill Gates Says Anti-Vaccine Effort Kills Children", 
         :author => authors[2],
         :body => "CNN has an interesting interview with Bill Gates who says that unbelievable progress is being made in both inventing new vaccines and making sure they get out to all the children who need them. The improvements could cut the number of children who die every year from about 9 million to half that. But Gates has harsh words for those who engage in anti-vaccine efforts, especially Dr. Andrew Wakefield, who falsified data to 'prove' a fraudulent link between vaccines and autism. 'It's an absolute lie that has killed thousands of kids,' says Gates. 'Because the mothers who heard that lie, many of them didn't have their kids take either pertussis or measles vaccine, and their children are dead today."
        },
        {:title => "US Gov't Pushing News Through China's Great Firewall",
         :author => authors[3],
         :body => "The US government's Broadcasting Board of Governors has revealed in a completed FOIA request the development, testing and planned use of Feed Over E-mail (FOE) to push news through China's firewall. This FOIA request (PDF) indicates that the US government is interested in making sure Chinese people receive up-to-date news, and it wants to expand the arsenal of anti-censorship tools (for news at least). The FOE project is GPLv3 and maintained by Sho Ho of BBG."
        },
        {:title => "Pentagon Sets Tone For Future Space Exploration",
         :author => authors[6],
         :body => "It obviously leans heavily on the military's concerns for outer space exploration, but the National Security Space Strategy (PDF) released yesterday by the Department of Defense outlines concerns like protection from space junk and system security that all space travelers in theory would want addressed. The NSSS document emphasizes the Obama administration's desire to protect US space assets and to further commercialize space but also to ensure that the US and international partners have unfettered access to outer space."
        },
				{:title => "The Most Violent Video Games of All Time",
				 :author => authors[7],
				 :body => "Switzerland and Australia already feel that violent video games are an issue, and in June the US Supreme Court will also take matters in its own hands. Revisiting some of the most violent video games made over the last couple of decades shows exactly why this is such a huge concern."
				},
				{:title => "Two Huge Holes in the Sun Spotted",
				 :author => authors[0],
				 :body => "Japanese scientists have spotted two huge holes on the sun's magnetic field, and it appears there is some reason to be concerned about. The holes, called coronal holes, are gateways for solar material and gas to spill out into space, according to space.com. The gaps in the sun's magnetic field make a hole through its atmosphere, letting gas out, NASA has said."
				},
				{:title => "The Dirty Little Secrets of Search", 
				 :author => authors[2],
				 :body => "The NY Times has an interesting story (reg. may be required) about how J. C. Penny used link farms to become the number one google search result for such terms as 'dresses,' 'bedding,' and 'samsonite carry on luggage' and what google did to them when they found out. 'Actually, it's the most ambitious attempt I've ever heard of,' says Doug Pierce, an expert in online search. 'This whole thing just blew me away. Especially for such a major brand. You'd think they would have people around them that would know better.'"
				},
				{:title => "Anonymous Claims Possession of Stuxnet Worm",
				 :author => authors[0],
				 :body => "Last night, a member of hacker group Anonymous announced on Twitter that the group was in possession of the Stuxnet worm. Recently, Anonymous has been in the news for its high profile attacks on software security firm HBGary, after Aaron Barr, the CEO of HBGary's sister firm HBGary Federal, claimed to have acquired the names of senior Anonymous members and threatened to release them to the public. This is where the possibility for Anonymous getting its hands on Stuxnet increases."
				},
				{:title => "Pandora Files for IPO",
				 :author => authors[4],
				 :body => "Internet radio service Pandora Media on Friday filed documents with the SEC for an initial public offering of common stock. In its S-1 filing, Pandora said it has more than 80 million registered users and a more than '50% share of all internet radio listening time among the top 20 stations and networks in the United States.' While Pandora said the 'number of shares to be offered and the price range for the offering have not yet been determined,' MarketWatch reports that the music service hopes to raise up to $100 million."
				},
				{:title => "HP Donates To WebOS's Major Homebrewing Group", 
				 :author => authors[5],
				 :body => "Internet radio service Pandora Media on Friday filed documents with the SEC for an initial public offering of common stock. In its S-1 filing, Pandora said it has more than 80 million registered users and a more than '50% share of all internet radio listening time among the top 20 stations and networks in the United States.' While Pandora said the 'number of shares to be offered and the price range for the offering have not yet been determined,' MarketWatch reports that the music service hopes to raise up to $100 million."
				}
    ])
